name: Build RewindPS4 Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Build proxy AAR
        working-directory: golang_proxy_server
        run: |
          go mod init yurisa
          go get github.com/elazarl/goproxy
          go get -tool golang.org/x/mobile/cmd/gobind
          go mod tidy
          gomobile bind -target=android -o ../app/golang_aar/proxy.aar .

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RewindPS4-fixed
          path: app/build/outputs/apk/debug/app-debug.apk
